[program:gsm-center-api]
directory = /root/gsm-center
command = bash run_api.sh
stdout_logfile = /var/log/supervisor/gsm-center-api.log
redirect_stderr = true
stopasgroup = true

[program:gsm-center-loop]
directory = /root/gsm-center
command = bash run_loop.sh
stdout_logfile = /var/log/supervisor/gsm-center-loop.log
redirect_stderr = true
stopasgroup = true
